### PR TITLE
commons #93 scalatest uri matcher

### PR DESCRIPTION
**Pull request by cerveada**

### CODE REVIEW

**Comment by wajda** [comment]
Could you also add en example to the Readme please?

**Comment by cerveada** [comment]
> Could you also add en example to the Readme please?

done

**Review by wajda — APPROVED** [review]
LGTM

**Comment by benedeki** [comment]
I was thinking about it. Would say the content of the scalatest folder should be in its own module. e.g. `absa-commons-test`. This probably shouldn't need to be part of the main branch of the program.  🤔

**Comment by wajda** [comment]
> I was thinking about it. Would say the content of the scalatest folder should be in its own module. e.g. `absa-commons-test`. This probably shouldn't need to be part of the main branch of the program. thinking

What do you mean by the "main branch of the program"?
_Commons_ is currently a single module project, are you suggesting to break it into multiple modules? We discussed that a while ago, and it certainly would be a logical step forward. There however are about a dozen fine grained packages in the project. We'd need to come up with a sensible break down to modules such that circular dependencies are eliminated and it everything fits together nicely. Provided that there are just one to a few classes per package, do you think it is all worth the efforts?

**Comment by benedeki** [comment]
> > I was thinking about it. Would say the content of the scalatest folder should be in its own module. e.g. `absa-commons-test`. This probably shouldn't need to be part of the main branch of the program. thinking
> 
> What do you mean by the "main branch of the program"? _Commons_ is currently a single module project, are you suggesting to break it into multiple modules? We discussed that a while ago, and it certainly would be a logical step forward. There however are about a dozen fine grained packages in the project. We'd need to come up with a sensible break down to modules such that circular dependencies are eliminated and it everything fits together nicely. Provided that there are just one to a few classes per package, do you think it is all worth the efforts?

Yes, multimodule, but not really fine-grained. Only two modules:
* general usage stuff
* test specific stuff - like the content of this PR
The point is, that you probably don't want to include these test classes and functions in the release of the project (the project that includes the commons lib).

**Comment by wajda** [comment]
> Yes, multimodule, but not really fine-grained. Only two modules:
> 
> * general usage stuff
> * test specific stuff - like the content of this PR
>   The point is, that you probably don't want to include these test classes and functions in the release of the project (the project that includes the commons lib).

Filed a separate ticket #95.
I completely agree with you, it certainly makes sense. But just to justify my lack of rushing into this, considering that all transient dependencies are marked _optional_ we are only talking about 204Kb of scalatest related bytecode, that in comparison with the size of other packages doesn't make it anything special in that regard.
```shell
❯ du -ch target/classes/za/co/absa/commons/ | sort -n -r
340K	target/classes/za/co/absa/commons/config
244K	target/classes/za/co/absa/commons/reflect
216K	target/classes/za/co/absa/commons/version
204K	target/classes/za/co/absa/commons/scalatest
172K	target/classes/za/co/absa/commons/lang
144K	target/classes/za/co/absa/commons/json
96K	target/classes/za/co/absa/commons/json/format
80K	target/classes/za/co/absa/commons/graph
76K	target/classes/za/co/absa/commons/version/impl
56K	target/classes/za/co/absa/commons/reflect/extractors
56K	target/classes/za/co/absa/commons/buildinfo
40K	target/classes/za/co/absa/commons/s3
28K	target/classes/za/co/absa/commons/io
24K	target/classes/za/co/absa/commons/error
16K	target/classes/za/co/absa/commons/annotation
1.6M	total
1.6M	target/classes/za/co/absa/commons/
```

**Comment by benedeki** [comment]
Thank for #95,
Just as a closure. I don't mean mostly as size safer, but logical separation. 😉

**Comment by cerveada** [comment]
@benedeki there is a special ticket for commons fragmentation, is there anything else you want to discuss? If not, could you please approve this PR?

**Review by dk1844 — APPROVED** [review]
LGTM (just read the code)

**Pull request merged**
